version: '2'
services:
    releasevitals-app:
        image: releasevitals
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://releasevitals-postgresql:5432/ReleaseVitals
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://releasevitals-elasticsearch:9200
        ports:
            - 8080:8080
    releasevitals-postgresql:
        extends:
            file: postgresql.yml
            service: releasevitals-postgresql
    releasevitals-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: releasevitals-elasticsearch
